events {}

http {
    server {
        listen 80;
        root /usr/share/nginx/html;
        index index.html;

        location = /favicon.ico {
            return 204;
        }

        location /hello {
            proxy_pass http://api:8090/hello;
        }

        location /headers {
            proxy_pass http://api:8090/headers;
        }

        location /save {
            proxy_pass http://api:8090/save;
        }
    }
}
